#PATH to all data
data_dir: /tmp/data

########## IMPORT DATA TO CONTENTFUL ##########

#Contentful credentials
access_token: <ACCESS_TOKEN>
organization_id: <ORGANIZATION_ID>


########## EXPORT DATA ##########

#Connecting to a database
adapter: mysql2
host: localhost
database: recipes_wildeisen_ch
user: root
password:

# adapter: mysql2, postgres,sqlite
# user: username
# host: localhost
# database: database_name
# password: root

mapped:
 tables:
  - :user_wildeisen_alergic_info
  - :user_wildeisen_ingredient
  - :user_wildeisen_recipe
  - :user_wildeisen_recipe_to_alergic_info
  - :user_wildeisen_recipe_to_ingredient
  - :user_wildeisen_unit

## MAPPING ##

# JSON file with mapping structure
# define relations between models
# check README
mapping_dir: contentful_import_files/mapping.json

#JSON file with contentful structure
contentful_structure_dir: contentful_import_files/contentful_structure.json

## CONVERT CONTENT TYPES JSON TO IMPORT FORM

#dump JSON file with content types from contentful model
#created by: curl -X GET \
#                 -H 'Authorization: Bearer ACCESS_TOKEN' \
#                 'https://api.contentful.com/spaces/SPACE_ID/content_types' > contentful_model.json
json_with_content_types: contentful_import_files/contentful_model.json

#PATH to save converted dump_file with content types
import_form_dir: contentful_import_files/contentful_structure.json