#PATH to all data
data_dir: /tmp/data

########## IMPORT DATA TO CONTENTFUL ##########

#Contentful credentials
access_token: <ACCESS_TOKEN>
organization_id: <ORGANIZATION_ID>

space_id: 36ochuqffqcb

########## EXPORT DATA ##########

#Connecting to a database
adapter: mysql2
host: localhost
#database: recipes_wildeisen_ch
database: recipes
user: root
password:

# adapter: mysql2, postgres,sqlite
# user: username
# host: localhost
# database: database_name
# password: root

mapped:
 tables:
  - :user_wildeisen_alergic_info
  - :user_wildeisen_ingredient
  - :user_wildeisen_recipe
  - :user_wildeisen_recipe_to_alergic_info
  - :user_wildeisen_recipe_to_ingredient
  - :user_wildeisen_unit

## MAPPING ##

mapping_dir: contentful_import_files/mapping.json

contentful_structure_dir: contentful_import_files/contentful_structure.json

json_with_content_types: contentful_import_files/contentful_model.json

import_form_dir: contentful_import_files/contentful_structure.json