#path to all data
data_dir: /tmp/data

########## IMPORT DATA TO CONTENTFUL ##########

#Contentful credentials
access_token: <ACCESS_TOKEN>
organization_id: <ORGANIZATION_ID>


########## EXPORT DATA ##########

#adapter: mysql2, postgres,sqlite
#user: username
#host: localhost
#database: database_name
#password: root

mapped:
tables:
  - :user_wildeisen_alergic_info
  - :user_wildeisen_ingredient
  - :user_wildeisen_recipe
  - :user_wildeisen_recipe_to_alergic_info
  - :user_wildeisen_recipe_to_ingredient
  - :user_wildeisen_unit

#file with mapping strucutre
mapping_dir: mapping.json

#file with contentful structure
contentful_structure_dir: contentful_structure.json

#dump file with content types from contentful model
json_with_content_types: contentful_dump.json

#path to save converted dump_file with content types
import_form_dir: contentful_structure.json
