#PATH to all data
data_dir: /tmp/data

########## IMPORT DATA TO CONTENTFUL ##########

#Contentful credentials - Define before import data to Contentful.
access_token:
organization_id:
space_id:
default_locale: 'locale-code'

## CONVERT CONTENT MODEL TO CONTENT TYPES JSON FILES
content_model_json:
import_form_dir:


## WORDPRESS
contentful_structure_dir: /Users/piotrprotas/rails_to_contentful/wordpress_settings/contentful_structure.json
wordpress_xml_path: /Users/piotrprotas/rails_to_contentful/wordpress_settings/wordpress.xml
