#PATH to all data
data_dir:

########## IMPORT DATA TO CONTENTFUL ##########

#Contentful credentials - Define before import data to Contentful.
access_token:
organization_id:
space_id:
default_locale:

## CONVERT CONTENT MODEL TO CONTENT TYPES JSON FILES
content_model_json:
import_form_dir:


## WORDPRESS
contentful_structure_dir:
wordpress_xml_path:
