#PATH to all data
data_dir: import_files

########## IMPORT DATA TO CONTENTFUL ##########

#Contentful credentials - Define before import data to Contentful.
access_token: ACCESS_TOKEN
organization_id: ORGANIZATION_ID
space_id: DEFINE_AFTER_CREATING_SPACE
default_locale: DEFINE_LOCALE_CODE

## CONVERT CONTENTFUL MODEL TO CONTENTFUL IMPORT STRUCTURE
content_model_json:
import_form_dir:

contentful_structure_dir:

mapping_dir: example_settings/mapping.json
contentful_structure_dir: example_settings/contentful_structure.json

