#PATH to all data
data_dir: PATH_TO_ALL_DATA

########## IMPORT DATA TO CONTENTFUL ##########

#Contentful credentials - Define before import data to Contentful.
access_token: ACCESS_TOKEN
organization_id: ORGANIZATION_ID
space_id: DEFINE_AFTER_CREATING_SPACE
default_locale: DEFINE_LOCALE_CODE

## CONVERT CONTENTFUL MODEL TO CONTENTFUL IMPORT STRUCTURE
content_model_json: example_settings/contentful_model.json
import_form_dir: example_settings/contentful_structure.json

mapping_dir: example_settings/mapping.json
contentful_structure_dir: example_settings/contentful_structure.json

