adapter: mysql2
user: szpryc
host: localhost
database: recipes
password: root


# adapter: mysql2, postgres,sqlite
# user: username
# host: localhost
# database: database_name
# password: root

data_dir: /tmp/data

json_with_content_types: '/Users/piotrprotas/Desktop/wildeisen.json'
import_form_dir: '/Users/piotrprotas/Desktop/contentful_form.json'