#PATH to all data
data_dir: DEFINE_BEFORE_EXPORTING_DATA


########## IMPORT DATA TO CONTENTFUL ##########

#Contentful credentials - Define before import data to Contentful.
access_token:
organization_id:
space_id: DEFINE_AFTER_CREATING_SPACE


########## EXPORT DATA ##########

#Connecting to a database
adapter: mysql2
host: localhost
database: database_name
user: username
password:


# Extract data from models:
mapped:
  tables:
  - :example_model_name
  - :example_model_name_two


## MAPPING ##
mapping_dir: /rails_to_contentful/example_data/mapping.json
contentful_structure_dir: /rails_to_contentful/example_data/contentful_structure.json


## CONVERT
content_model_json:
import_form_dir:
