#PATH to all data
data_dir:


########## IMPORT DATA TO CONTENTFUL ##########

#Contentful credentials - Define before import data to Contentful.
access_token:
organization_id:
space_id:
default_locale: 'locale-code'

########## EXPORT DATA ##########

#Connecting to a database
adapter: mysql2
host: localhost
database: database_name
user: username
password:


# Extract data from models:
mapped:
  tables:
  - :example_model_name
  - :example_model_name_two


## MAPPING ##
mapping_dir:
contentful_structure_dir:


## CONVERT
content_model_json:
import_form_dir:


## WORDPRESS

wordpress_xml_path: