#PATH to all data
data_dir: /tmp/data


########## IMPORT DATA TO CONTENTFUL ##########

#Contentful credentials - Define before import data to Contentful.
access_token:
organization_id:
space_id: DEFINE_AFTER_CREATING_SPACE


########## EXPORT DATA ##########

#Connecting to a database
adapter: mysql2
host: localhost
database: database_name
user: username
password:


# Extract data from models:
mapped:
  tables:
  - :example_model_name
  - :example_model_name_two


## MAPPING ##
mapping_dir: /Users/piotrprotas/rails_to_contentful/example_data/mapping.json
contentful_structure_dir: /Users/piotrprotas//rails_to_contentful/example_data/contentful_structure.json


## CONVERT
content_model_json: /Users/piotrprotas//rails_to_contentful/example_data/contentful_model.json
import_form_dir: /Users/piotrprotas//rails_to_contentful/example_data/contentful_structure.json


## WORDPRESS

wordpress_xml_path: /Users/piotrprotas//rails_to_contentful/example_data/wordpress.xml